<a href="https://colab.research.google.com/github/vit050587/PyTorch/blob/master/KVA_PYTORCH_HW_01_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5
x = torch.randn(3, 4, 5)
x, x.type()

(tensor([[[ 0.6400, -0.0269, -0.3201,  0.9135,  0.6278],
          [ 0.1552, -0.7653, -0.2313,  0.8182,  0.1330],
          [-0.6433, -0.4754,  0.9673,  1.3043,  0.1552],
          [ 1.2471,  1.1486, -1.3232,  0.8649, -1.6233]],
 
         [[ 0.6398, -1.0307, -0.9616,  1.7828, -0.4826],
          [ 0.8068, -0.6841, -0.4834,  0.1119, -0.4788],
          [-0.4754,  1.7196, -1.2248, -0.2131,  2.8287],
          [-0.0761,  0.6124, -0.7852, -0.7969, -0.7072]],
 
         [[-0.5401, -0.5569,  0.6075,  0.2805, -0.7019],
          [-1.1090,  0.1342, -0.0086,  0.1948,  1.0765],
          [ 0.6853, -1.2651, -0.6639,  2.0174, -0.4348],
          [-0.3908, -1.0491, -0.5701,  1.8960,  1.4356]]]),
 'torch.FloatTensor')

In [3]:
# 2. Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [4]:
# 3. Приведите его к форме 6х10
x = x.reshape(6, 10)
x

tensor([[ 0.6400, -0.0269, -0.3201,  0.9135,  0.6278,  0.1552, -0.7653, -0.2313,
          0.8182,  0.1330],
        [-0.6433, -0.4754,  0.9673,  1.3043,  0.1552,  1.2471,  1.1486, -1.3232,
          0.8649, -1.6233],
        [ 0.6398, -1.0307, -0.9616,  1.7828, -0.4826,  0.8068, -0.6841, -0.4834,
          0.1119, -0.4788],
        [-0.4754,  1.7196, -1.2248, -0.2131,  2.8287, -0.0761,  0.6124, -0.7852,
         -0.7969, -0.7072],
        [-0.5401, -0.5569,  0.6075,  0.2805, -0.7019, -1.1090,  0.1342, -0.0086,
          0.1948,  1.0765],
        [ 0.6853, -1.2651, -0.6639,  2.0174, -0.4348, -0.3908, -1.0491, -0.5701,
          1.8960,  1.4356]])

In [5]:
# 4. Создайте случайный IntTensor размера 10
a = torch.randint(10, size=(10,)).type(torch.IntTensor)
a, a.type()

(tensor([6, 2, 1, 6, 7, 3, 7, 0, 7, 2], dtype=torch.int32), 'torch.IntTensor')

In [6]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
xa = x * a
xa

tensor([[ 3.8399, -0.0538, -0.3201,  5.4810,  4.3947,  0.4657, -5.3568, -0.0000,
          5.7277,  0.2661],
        [-3.8599, -0.9509,  0.9673,  7.8257,  1.0864,  3.7412,  8.0399, -0.0000,
          6.0541, -3.2466],
        [ 3.8386, -2.0613, -0.9616, 10.6969, -3.3782,  2.4205, -4.7889, -0.0000,
          0.7834, -0.9576],
        [-2.8526,  3.4392, -1.2248, -1.2788, 19.8009, -0.2283,  4.2870, -0.0000,
         -5.5783, -1.4143],
        [-3.2403, -1.1138,  0.6075,  1.6831, -4.9132, -3.3270,  0.9393, -0.0000,
          1.3635,  2.1531],
        [ 4.1115, -2.5302, -0.6639, 12.1045, -3.0434, -1.1724, -7.3439, -0.0000,
         13.2718,  2.8713]])

In [7]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
xa_xa = xa @ xa.T
xa_xa

tensor([[ 125.9931,   25.0733,   89.9542,   13.8661,  -23.1423,  184.6800],
        [  25.0733,  204.9884,   44.6597,   22.4936,   18.3569,   84.9092],
        [  89.9542,   44.6597,  176.0682, -121.5302,   10.3303,  201.3780],
        [  13.8661,   22.4936, -121.5302,  466.7232, -100.6335, -204.6674],
        [ -23.1423,   18.3569,   10.3303, -100.6335,   57.5273,   45.6980],
        [ 184.6800,   84.9092,  201.3780, -204.6674,   45.6980,  419.2202]])

In [8]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1.], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.], requires_grad=True)

y = x**3 + z - 75*t

y.backward()

print('dy/dx: ', x.grad)
print('dy/dz: ', z.grad)
print('dy/dt: ', t.grad)

dy/dx:  tensor([3.])
dy/dz:  tensor([1.])
dy/dt:  tensor([-75.])


In [9]:
# 8. Создайте единичный тензор размера 5x6
t_ones = torch.ones(5, 6)
t_ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [10]:
# 9. Переведите его в формат numpy
t_ones = t_ones.numpy()
t_ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)